# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
"""Data models for the Smart Selection Engine.

These dataclasses represent the core data structures used for indexing
images, tracking sources, storing color palettes, and defining selection
constraints.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any


@dataclass
class ImageRecord:
    """Represents an indexed image with metadata and usage statistics.

    Attributes:
        filepath: Absolute path to the image file (primary key).
        filename: Just the filename portion.
        source_id: Identifier for the image source (e.g., 'unsplash', 'wallhaven').
        width: Image width in pixels.
        height: Image height in pixels.
        aspect_ratio: Width/height ratio for quick filtering.
        file_size: File size in bytes.
        file_mtime: File modification time (Unix timestamp).
        is_favorite: Whether the image is in the favorites folder.
        first_indexed_at: When the image was first indexed (Unix timestamp).
        last_indexed_at: When the image was last re-indexed (Unix timestamp).
        last_shown_at: When the image was last displayed (Unix timestamp).
        times_shown: Number of times this image has been displayed.
    """
    filepath: str
    filename: str
    source_id: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    aspect_ratio: Optional[float] = None
    file_size: Optional[int] = None
    file_mtime: Optional[int] = None
    is_favorite: bool = False
    first_indexed_at: Optional[int] = None
    last_indexed_at: Optional[int] = None
    last_shown_at: Optional[int] = None
    times_shown: int = 0


@dataclass
class SourceRecord:
    """Represents a wallpaper source with usage statistics.

    Used for source-level recency tracking to balance selection
    across different wallpaper sources.

    Attributes:
        source_id: Unique identifier for the source (primary key).
        source_type: Type of source ('local', 'unsplash', 'wallhaven', etc.).
        last_shown_at: When an image from this source was last shown.
        times_shown: Total number of times images from this source were shown.
    """
    source_id: str
    source_type: Optional[str] = None
    last_shown_at: Optional[int] = None
    times_shown: int = 0


@dataclass
class PaletteRecord:
    """Represents a wallust color palette for an image.

    Stores the 16-color palette generated by wallust plus derived
    metrics for fast color-based queries.

    Attributes:
        filepath: Path to the image (foreign key to ImageRecord).
        color0-color15: The 16 wallust palette colors as hex strings.
        background: Background color from wallust.
        foreground: Foreground color from wallust.
        cursor: Cursor color from wallust.
        avg_hue: Average hue across palette (0-360, circular mean).
        avg_saturation: Average saturation (0-1).
        avg_lightness: Average lightness (0-1).
        color_temperature: Derived temperature (-1=cool to +1=warm).
        indexed_at: When the palette was generated (Unix timestamp).
    """
    filepath: str
    color0: Optional[str] = None
    color1: Optional[str] = None
    color2: Optional[str] = None
    color3: Optional[str] = None
    color4: Optional[str] = None
    color5: Optional[str] = None
    color6: Optional[str] = None
    color7: Optional[str] = None
    color8: Optional[str] = None
    color9: Optional[str] = None
    color10: Optional[str] = None
    color11: Optional[str] = None
    color12: Optional[str] = None
    color13: Optional[str] = None
    color14: Optional[str] = None
    color15: Optional[str] = None
    background: Optional[str] = None
    foreground: Optional[str] = None
    cursor: Optional[str] = None
    avg_hue: Optional[float] = None
    avg_saturation: Optional[float] = None
    avg_lightness: Optional[float] = None
    color_temperature: Optional[float] = None
    indexed_at: Optional[int] = None


@dataclass
class SelectionConstraints:
    """Constraints for filtering images during selection.

    Used to specify requirements for image selection such as
    minimum dimensions, aspect ratio range, and color preferences.

    Attributes:
        min_width: Minimum image width in pixels.
        min_height: Minimum image height in pixels.
        min_aspect_ratio: Minimum aspect ratio (width/height).
        max_aspect_ratio: Maximum aspect ratio (width/height).
        target_palette: Target palette for color similarity matching.
        min_color_similarity: Minimum color similarity threshold (0-1).
            Only used when target_palette is set. Images with palettes
            below this similarity are excluded. Default is 0.5.
        sources: List of source_ids to include (None = all sources).
        favorites_only: If True, only select from favorites.
    """
    min_width: Optional[int] = None
    min_height: Optional[int] = None
    min_aspect_ratio: Optional[float] = None
    max_aspect_ratio: Optional[float] = None
    target_palette: Optional[Dict[str, Any]] = None
    min_color_similarity: Optional[float] = None
    sources: Optional[List[str]] = None
    favorites_only: bool = False


@dataclass
class IndexingResult:
    """Result of an incremental indexing operation.

    Attributes:
        added: Number of new files indexed.
        updated: Number of existing files re-indexed (mtime changed).
        removed: Number of files removed from index (no longer on disk).
        errors: Number of files that failed to index.
    """
    added: int = 0
    updated: int = 0
    removed: int = 0
    errors: int = 0
