# -*- Mode: Python; coding: utf-8; indent-tabs-mode: nil; tab-width: 4 -*-
"""Data models for the Smart Selection Engine.

These dataclasses represent the core data structures used for indexing
images, tracking sources, storing color palettes, and defining selection
constraints.
"""

from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any


@dataclass
class ImageRecord:
    """Represents an indexed image with metadata and usage statistics.

    Attributes:
        filepath: Absolute path to the image file (primary key).
        filename: Just the filename portion.
        source_id: Identifier for the image source (e.g., 'unsplash', 'wallhaven').
        width: Image width in pixels.
        height: Image height in pixels.
        aspect_ratio: Width/height ratio for quick filtering.
        file_size: File size in bytes.
        file_mtime: File modification time (Unix timestamp).
        is_favorite: Whether the image is in the favorites folder.
        first_indexed_at: When the image was first indexed (Unix timestamp).
        last_indexed_at: When the image was last re-indexed (Unix timestamp).
        last_shown_at: When the image was last displayed (Unix timestamp).
        times_shown: Number of times this image has been displayed.
        palette_status: Status of palette extraction ('pending', 'extracted', 'failed').
            Images with 'pending' or 'failed' status are excluded from time-based selection.
    """
    filepath: str
    filename: str
    source_id: Optional[str] = None
    width: Optional[int] = None
    height: Optional[int] = None
    aspect_ratio: Optional[float] = None
    file_size: Optional[int] = None
    file_mtime: Optional[int] = None
    is_favorite: bool = False
    first_indexed_at: Optional[int] = None
    last_indexed_at: Optional[int] = None
    last_shown_at: Optional[int] = None
    times_shown: int = 0
    palette_status: str = 'pending'  # 'pending', 'extracted', 'failed'


@dataclass
class SourceRecord:
    """Represents a wallpaper source with usage statistics.

    Used for source-level recency tracking to balance selection
    across different wallpaper sources.

    Attributes:
        source_id: Unique identifier for the source (primary key).
        source_type: Type of source ('local', 'unsplash', 'wallhaven', etc.).
        last_shown_at: When an image from this source was last shown.
        times_shown: Total number of times images from this source were shown.
    """
    source_id: str
    source_type: Optional[str] = None
    last_shown_at: Optional[int] = None
    times_shown: int = 0


@dataclass
class PaletteRecord:
    """Represents a wallust color palette for an image.

    Stores the 16-color palette generated by wallust plus derived
    metrics for fast color-based queries.

    Attributes:
        filepath: Path to the image (foreign key to ImageRecord).
        color0-color15: The 16 wallust palette colors as hex strings.
        background: Background color from wallust.
        foreground: Foreground color from wallust.
        cursor: Cursor color from wallust.
        avg_hue: Average hue across palette (0-360, circular mean).
        avg_saturation: Average saturation (0-1).
        avg_lightness: Average lightness (0-1).
        color_temperature: Derived temperature (-1=cool to +1=warm).
        indexed_at: When the palette was generated (Unix timestamp).
    """
    filepath: str
    color0: Optional[str] = None
    color1: Optional[str] = None
    color2: Optional[str] = None
    color3: Optional[str] = None
    color4: Optional[str] = None
    color5: Optional[str] = None
    color6: Optional[str] = None
    color7: Optional[str] = None
    color8: Optional[str] = None
    color9: Optional[str] = None
    color10: Optional[str] = None
    color11: Optional[str] = None
    color12: Optional[str] = None
    color13: Optional[str] = None
    color14: Optional[str] = None
    color15: Optional[str] = None
    background: Optional[str] = None
    foreground: Optional[str] = None
    cursor: Optional[str] = None
    avg_hue: Optional[float] = None
    avg_saturation: Optional[float] = None
    avg_lightness: Optional[float] = None
    color_temperature: Optional[float] = None
    perceived_brightness: Optional[float] = None
    brightness_p10: Optional[float] = None
    brightness_p90: Optional[float] = None
    pixel_warm_ratio: Optional[float] = None
    pixel_chroma_median: Optional[float] = None
    pixel_hue_entropy: Optional[float] = None
    pixel_dominant_hue: Optional[float] = None
    pixel_temperature: Optional[float] = None
    indexed_at: Optional[int] = None

    def to_dict(self, include_metrics: bool = False) -> Dict[str, str]:
        """Convert to palette dict with color0-15, background, foreground, cursor.

        Returns a dict containing only the color keys that have non-None values.
        Internal fields (filepath, indexed_at) are excluded.

        Args:
            include_metrics: If True, include avg_hue, avg_saturation,
                            avg_lightness, color_temperature, and brightness fields.

        Returns:
            Dict with non-None color keys and optionally metric keys.
        """
        result = {}
        for i in range(16):
            value = getattr(self, f'color{i}')
            if value is not None:
                result[f'color{i}'] = value
        for key in ('background', 'foreground', 'cursor'):
            value = getattr(self, key)
            if value is not None:
                result[key] = value
        if include_metrics:
            for key in ('avg_hue', 'avg_saturation', 'avg_lightness',
                        'color_temperature', 'perceived_brightness',
                        'brightness_p10', 'brightness_p90',
                        'pixel_warm_ratio', 'pixel_chroma_median',
                        'pixel_hue_entropy', 'pixel_dominant_hue',
                        'pixel_temperature'):
                value = getattr(self, key)
                if value is not None:
                    result[key] = value
        return result


@dataclass
class ColorThemeRecord:
    """Represents a terminal/editor color theme for reverse theming.

    Stores the 16 ANSI colors plus background/foreground/cursor from
    a theme definition (e.g., Zed theme, custom, or imported). Derived
    metrics enable color-based filtering and matching with image palettes.

    Attributes:
        theme_id: Unique identifier for the theme (primary key).
        name: Human-readable theme name.
        source_type: Origin type ('zed', 'custom', 'imported').
        source_path: Path to the original theme file, if applicable.
        appearance: Theme appearance ('dark', 'light').
        color0-color15: The 16 ANSI colors as hex strings.
        background: Background color.
        foreground: Foreground color.
        cursor: Cursor color.
        avg_hue: Average hue across palette (0-360, circular mean).
        avg_saturation: Average saturation (0-1).
        avg_lightness: Average lightness (0-1).
        color_temperature: Derived temperature (-1=cool to +1=warm).
        imported_at: When the theme was imported (Unix timestamp).
        is_custom: Whether this is a user-customized theme.
        parent_theme_id: ID of the parent theme if this is a customization.
    """
    theme_id: str
    name: str
    source_type: str  # 'zed', 'custom', 'imported'
    source_path: Optional[str] = None
    appearance: Optional[str] = None  # 'dark', 'light'
    color0: Optional[str] = None
    color1: Optional[str] = None
    color2: Optional[str] = None
    color3: Optional[str] = None
    color4: Optional[str] = None
    color5: Optional[str] = None
    color6: Optional[str] = None
    color7: Optional[str] = None
    color8: Optional[str] = None
    color9: Optional[str] = None
    color10: Optional[str] = None
    color11: Optional[str] = None
    color12: Optional[str] = None
    color13: Optional[str] = None
    color14: Optional[str] = None
    color15: Optional[str] = None
    background: Optional[str] = None
    foreground: Optional[str] = None
    cursor: Optional[str] = None
    avg_hue: Optional[float] = None
    avg_saturation: Optional[float] = None
    avg_lightness: Optional[float] = None
    color_temperature: Optional[float] = None
    imported_at: Optional[int] = None
    is_custom: bool = False
    parent_theme_id: Optional[str] = None

    def to_dict(self, include_metrics: bool = False) -> Dict[str, str]:
        """Convert to palette dict with color0-15, background, foreground, cursor.

        Returns a dict containing only the color keys that have non-None values.
        Compatible with TemplateProcessor and PaletteRecord.to_dict() protocol.

        Args:
            include_metrics: If True, include avg_hue, avg_saturation,
                            avg_lightness, color_temperature.

        Returns:
            Dict with non-None color keys and optionally metric keys.
        """
        result = {}
        for i in range(16):
            value = getattr(self, f'color{i}')
            if value is not None:
                result[f'color{i}'] = value
        for key in ('background', 'foreground', 'cursor'):
            value = getattr(self, key)
            if value is not None:
                result[key] = value
        if include_metrics:
            for key in ('avg_hue', 'avg_saturation', 'avg_lightness', 'color_temperature'):
                value = getattr(self, key)
                if value is not None:
                    result[key] = value
        return result


# Theme adherence levels: maps user-facing label to min_color_similarity threshold.
# Used by theme browser UI, VarietyWindow constraint builder, and match counting.
# None means no color filtering (templates only, all wallpapers eligible).
#
# Thresholds are calibrated for HSL metric comparison (palette_similarity_hsl),
# which produces values in the ~0.50-0.90 range when comparing terminal themes
# against wallpaper palettes. OKLAB individual-color matching produces compressed
# values (~0.70-0.95) that don't discriminate mood differences well.
ADHERENCE_LEVELS = {
    'off': None,
    'loose': 0.60,
    'moderate': 0.70,
    'strict': 0.80,
}

# Ordered list for UI combo boxes: (label, threshold)
ADHERENCE_CHOICES = [
    ("Off", None),
    ("Loose", 0.60),
    ("Moderate", 0.70),
    ("Strict", 0.80),
]


@dataclass
class SelectionConstraints:
    """Constraints for filtering images during selection.

    Used to specify requirements for image selection such as
    minimum dimensions, aspect ratio range, and color preferences.

    Attributes:
        min_width: Minimum image width in pixels.
        min_height: Minimum image height in pixels.
        min_aspect_ratio: Minimum aspect ratio (width/height).
        max_aspect_ratio: Maximum aspect ratio (width/height).
        target_palette: Target palette for color similarity matching.
        min_color_similarity: Minimum color similarity threshold (0-1).
            Only used when target_palette is set. Images with palettes
            below this similarity are excluded. Default is 0.5.
        min_lightness: Minimum average lightness (0-1). Images darker than
            this are excluded. Used by adaptive time-of-day mode to enforce
            brightness floors (e.g. morning wants bright wallpapers).
        max_lightness: Maximum average lightness (0-1). Images brighter than
            this are excluded. Used by adaptive time-of-day mode to enforce
            brightness ceilings (e.g. night wants dark wallpapers).
        max_brightness_p90: Maximum 90th-percentile brightness (0-1). Rejects
            images with bright regions even if median brightness is low.
            Used by night mode to catch mostly-dark images with blinding spots.
        sources: List of source_ids to include (None = all sources).
        favorites_only: If True, only select from favorites.
    """
    min_width: Optional[int] = None
    min_height: Optional[int] = None
    min_aspect_ratio: Optional[float] = None
    max_aspect_ratio: Optional[float] = None
    target_palette: Optional[Dict[str, Any]] = None
    min_color_similarity: Optional[float] = None
    min_lightness: Optional[float] = None
    max_lightness: Optional[float] = None
    max_brightness_p90: Optional[float] = None
    sources: Optional[List[str]] = None
    favorites_only: bool = False


@dataclass
class IndexingResult:
    """Result of an incremental indexing operation.

    Attributes:
        added: Number of new files indexed.
        updated: Number of existing files re-indexed (mtime changed).
        removed: Number of files removed from index (no longer on disk).
        errors: Number of files that failed to index.
    """
    added: int = 0
    updated: int = 0
    removed: int = 0
    errors: int = 0
